In [1]:
import pandas as pd
import glob
import os

In [2]:
path = "HUPA-UC Diabetes Dataset/*.csv"
import glob

files = glob.glob(path)
print(files[:5])

['HUPA-UC Diabetes Dataset\\HUPA0001P.csv', 'HUPA-UC Diabetes Dataset\\HUPA0002P.csv', 'HUPA-UC Diabetes Dataset\\HUPA0003P.csv', 'HUPA-UC Diabetes Dataset\\HUPA0004P.csv', 'HUPA-UC Diabetes Dataset\\HUPA0005P.csv']

In [3]:
patient_files = [f for f in files if os.path.basename(f).startswith("HUPA")] # just taking files starting with HUPA
print("Patient monitoring files:", len(patient_files))

Patient monitoring files: 25

In [4]:
all_data = []

for file in patient_files:
    df = pd.read_csv(file, sep=';')
    
    patient_id = os.path.basename(file).replace(".csv","")
    df["Patient_ID"] = patient_id
    
    all_data.append(df)

master_df = pd.concat(all_data, ignore_index=True)

In [5]:

master_df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID
0,2018-06-13T18:40:00,332.0,6.3595,82.322835,34.0,0.091667,0.0,0.0,HUPA0001P
1,2018-06-13T18:45:00,326.0,7.7280,83.740157,0.0,0.091667,0.0,0.0,HUPA0001P
2,2018-06-13T18:50:00,330.0,4.7495,80.525180,0.0,0.091667,0.0,0.0,HUPA0001P
3,2018-06-13T18:55:00,324.0,6.3595,89.129032,20.0,0.091667,0.0,0.0,HUPA0001P
4,2018-06-13T19:00:00,306.0,5.1520,92.495652,0.0,0.075000,0.0,0.0,HUPA0001P

In [6]:
print(master_df.columns)

Index(['time', 'glucose', 'calories', 'heart_rate', 'steps', 'basal_rate',
       'bolus_volume_delivered', 'carb_input', 'Patient_ID'],
      dtype='object')

In [7]:
meta = pd.read_csv("HUPA-UC Diabetes Dataset/T1DM_patient_sleep_demographics_with_race.csv") # reading sleep demographics.csv 
print(meta.head())
print(meta.columns)

  Patient_ID  Age  Gender             Race  Average Sleep Duration (hrs)  \
0  HUPA0001P   34    Male            Other                           6.3
1  HUPA0002P   49    Male         Hispanic                           6.6
2  HUPA0003P   64    Male            Black                           5.3
3  HUPA0004P   34  Female  Native American                           5.2
4  HUPA0005P   49    Male  Native American                           5.8

   Sleep Quality (1-10)  % with Sleep Disturbances
0                   4.5                         80
1                   4.4                         40
2                   5.2                         70
3                   6.9                         60
4                   7.9                         30
Index(['Patient_ID', 'Age', 'Gender', 'Race', 'Average Sleep Duration (hrs)',
       'Sleep Quality (1-10)', '% with Sleep Disturbances'],
      dtype='object')

In [8]:
master_df = master_df.merge(meta, on="Patient_ID", how="left") # merging sleep demographics with the mater data frame

In [9]:
master_df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,2018-06-13T18:40:00,332.0,6.3595,82.322835,34.0,0.091667,0.0,0.0,HUPA0001P,34,Male,Other,6.3,4.5,80
1,2018-06-13T18:45:00,326.0,7.7280,83.740157,0.0,0.091667,0.0,0.0,HUPA0001P,34,Male,Other,6.3,4.5,80
2,2018-06-13T18:50:00,330.0,4.7495,80.525180,0.0,0.091667,0.0,0.0,HUPA0001P,34,Male,Other,6.3,4.5,80
3,2018-06-13T18:55:00,324.0,6.3595,89.129032,20.0,0.091667,0.0,0.0,HUPA0001P,34,Male,Other,6.3,4.5,80
4,2018-06-13T19:00:00,306.0,5.1520,92.495652,0.0,0.075000,0.0,0.0,HUPA0001P,34,Male,Other,6.3,4.5,80

In [10]:
master_df.to_csv('merged_data.csv', index=False)