# Data Cleaning and Preprocessing

In this notebook, we will perform the initial data cleaning and preprocessing steps for the HUPA-UC Diabetes Dataset. This includes loading the data, merging the different files, handling missing values and inconsistencies, and preparing the data for exploratory data analysis.

In [41]:
import pandas as pd
import numpy as np
import os
import glob

In [42]:
master_df = pd.read_csv('merged_data.csv')

In [43]:
master_df.shape # checking the number of rows and columns in the dataframe

(309392, 15)

## Dropping duplicate rows

In [44]:
master_df.drop_duplicates()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,2020-01-17T00:00:00,40.000000,15.04290,96.371901,8.0,0.035,0.0,1.0,HUPA0023P,74,Female,Black,5.1,6.8,40
1,2020-01-17T00:05:00,41.333333,8.31640,91.395349,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
2,2020-01-17T00:10:00,42.666667,7.58260,85.991935,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
3,2020-01-17T00:15:00,44.000000,7.33800,82.434426,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
4,2020-01-17T00:20:00,50.000000,7.58260,78.822581,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309387,2019-07-13T18:20:00,70.000000,13.58784,85.123967,61.0,0.152,0.0,0.0,HUPA0020P,29,Male,White,5.4,7.9,70
309388,2019-07-13T18:25:00,80.000000,6.57824,81.886179,0.0,0.152,0.0,0.0,HUPA0020P,29,Male,White,5.4,7.9,70
309389,2019-07-13T18:30:00,90.000000,6.90176,84.046154,0.0,0.152,0.0,0.0,HUPA0020P,29,Male,White,5.4,7.9,70
309390,2019-07-13T18:35:00,108.666667,6.47040,82.110236,0.0,0.152,0.0,0.0,HUPA0020P,29,Male,White,5.4,7.9,70
309391,2019-07-13T18:40:00,127.333333,5.60768,85.696970,0.0,0.152,0.0,0.0,HUPA0020P,29,Male,White,5.4,7.9,70

In [45]:
master_df.shape

(309392, 15)

Since there is no change in the shape of the dataframe before and after dropping duplicate rows, we can say that there are no duplicate rows in the dataset.

## Handle Missing Values

In [46]:
master_df.isnull().sum()

time                            0
glucose                         0
calories                        0
heart_rate                      0
steps                           0
basal_rate                      0
bolus_volume_delivered          0
carb_input                      0
Patient_ID                      0
Age                             0
Gender                          0
Race                            0
Average Sleep Duration (hrs)    0
Sleep Quality (1-10)            0
% with Sleep Disturbances       0
dtype: int64

From the above output we can confirm that the dataframe has no Null values.

In [47]:
master_df.dtypes

time                             object
glucose                         float64
calories                        float64
heart_rate                      float64
steps                           float64
basal_rate                      float64
bolus_volume_delivered          float64
carb_input                      float64
Patient_ID                       object
Age                               int64
Gender                           object
Race                             object
Average Sleep Duration (hrs)    float64
Sleep Quality (1-10)            float64
% with Sleep Disturbances         int64
dtype: object

## Handle Data Types
Converting the time column into proper datetime objects.

In [48]:
master_df['time'] = pd.to_datetime(master_df['time'])

In [49]:
master_df.dtypes

time                            datetime64[ns]
glucose                                float64
calories                               float64
heart_rate                             float64
steps                                  float64
basal_rate                             float64
bolus_volume_delivered                 float64
carb_input                             float64
Patient_ID                              object
Age                                      int64
Gender                                  object
Race                                    object
Average Sleep Duration (hrs)           float64
Sleep Quality (1-10)                   float64
% with Sleep Disturbances                int64
dtype: object

In [50]:
master_df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,2020-01-17 00:00:00,40.000000,15.0429,96.371901,8.0,0.035,0.0,1.0,HUPA0023P,74,Female,Black,5.1,6.8,40
1,2020-01-17 00:05:00,41.333333,8.3164,91.395349,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
2,2020-01-17 00:10:00,42.666667,7.5826,85.991935,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
3,2020-01-17 00:15:00,44.000000,7.3380,82.434426,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
4,2020-01-17 00:20:00,50.000000,7.5826,78.822581,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40

## Format Columns
We can see in the above output that columns glucose, calories and hear_rate have large decimal values. Here we are rounding these column values to 2 decimal places.

In [51]:
master_df['glucose'] = master_df['glucose'].round(2)
master_df['calories'] = master_df['calories'].round(2)
master_df['heart_rate'] = master_df['heart_rate'].round(2)

In [52]:
master_df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,2020-01-17 00:00:00,40.00,15.04,96.37,8.0,0.035,0.0,1.0,HUPA0023P,74,Female,Black,5.1,6.8,40
1,2020-01-17 00:05:00,41.33,8.32,91.40,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
2,2020-01-17 00:10:00,42.67,7.58,85.99,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
3,2020-01-17 00:15:00,44.00,7.34,82.43,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
4,2020-01-17 00:20:00,50.00,7.58,78.82,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40

In [53]:
master_df.describe().T

,count,mean,min,25%,50%,75%,max,std
time,309392,2020-09-24 13:06:07.680159488,2018-06-13 18:40:00,2020-01-30 11:00:00,2020-10-31 16:52:30,2021-07-27 06:31:15,2022-05-18 12:15:00,NaN
glucose,309392.0,141.425051,40.0,99.67,132.0,173.0,444.0,57.085587
calories,309392.0,8.8131,0.0,5.85,6.28,9.19,106.35,6.930581
heart_rate,309392.0,76.990004,32.41,64.93,75.42,85.61,195.62,15.546697
steps,309392.0,30.825005,0.0,0.0,0.0,11.0,842.0,84.981109
basal_rate,309392.0,0.041324,0.0,0.0,0.056,0.066,0.25,0.036106
bolus_volume_delivered,309392.0,0.066058,-3.0,0.0,0.0,0.0,19.8,0.755075
carb_input,309392.0,0.052718,0.0,0.0,0.0,0.0,130.0,1.505433
Age,309392.0,53.332727,20.0,46.0,60.0,60.0,74.0,12.421322
Average Sleep Duration (hrs),309392.0,5.665791,5.0,5.5,5.5,5.9,7.2,0.450037
Sleep Quality (1-10),309392.0,5.916159,4.1,5.5,5.9,5.9,7.9,0.976449
% with Sleep Disturbances,309392.0,54.376972,30.0,50.0,60.0,60.0,80.0,12.299519

From the above output we can seee that bolus_volume_delivered has a negative minimun value. We know that bolus_volume_delivered is a specific, single dose of medication or fluid administered rapidly (typically over 1 to 30 minutes) to achieve a swift therapeutic effect. So this cannot be negative.

## Replacing negative values with 0

In [54]:
for value in master_df['bolus_volume_delivered']:
    if value < 0:
        print(value)

-1.0
-1.0
-3.0
-1.0

In [56]:
master_df[master_df['bolus_volume_delivered'] < 0] = 0

In [57]:
master_df.describe().T

,count,mean,std,min,25%,50%,75%,max
glucose,309392.0,141.423700,57.087659,0.0,99.67,132.000,173.000,444.00
calories,309392.0,8.813001,6.930636,0.0,5.85,6.280,9.190,106.35
heart_rate,309392.0,76.988772,15.549005,0.0,64.93,75.420,85.610,195.62
steps,309392.0,30.824734,84.981073,0.0,0.00,0.000,11.000,842.00
basal_rate,309392.0,0.041323,0.036106,0.0,0.00,0.056,0.066,0.25
bolus_volume_delivered,309392.0,0.066077,0.755047,0.0,0.00,0.000,0.000,19.80
carb_input,309392.0,0.052661,1.505341,0.0,0.00,0.000,0.000,130.00
Age,309392.0,53.331899,12.422743,0.0,46.00,60.000,60.000,74.00
Average Sleep Duration (hrs),309392.0,5.665716,0.450498,0.0,5.50,5.500,5.900,7.20
Sleep Quality (1-10),309392.0,5.916065,0.976668,0.0,5.50,5.900,5.900,7.90
% with Sleep Disturbances,309392.0,54.376325,12.301063,0.0,50.00,60.000,60.000,80.00

We can see that the negative values have been replaced by 0.

## 1.6 Save Cleaned Data

In [58]:
master_df.to_csv('cleaned_data.csv', index=False)