In [1]:
import pandas as pd
import zipfile
import glob
import os

In [2]:
# Path to ZIP file
zip_path = r"C:\Users\Pravallika Dheshidi\OneDrive\Desktop\python hackthon\HUPA-UC Diabetes Dataset.zip"
# Folder to extract files
extract_folder = r"C:\Users\Pravallika Dheshidi\OneDrive\Documents\GitHub\team9_PyCoders_PythonHackathon_MAY2026"
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

In [4]:
print("ZIP extracted successfully!")

ZIP extracted successfully!

In [5]:
# Get all CSV files
csv_files = glob.glob(os.path.join(extract_folder, "*.csv"))

In [10]:
print(os.listdir(extract_folder))

['.DS_Store', '.git', 'HUPA-UC Diabetes Dataset']

In [11]:
path = os.path.join(extract_folder, "HUPA-UC Diabetes Dataset", "*.csv")
files = glob.glob(path)

print(files[:5])

['C:\\Users\\Pravallika Dheshidi\\OneDrive\\Documents\\GitHub\\team9_PyCoders_PythonHackathon_MAY2026\\HUPA-UC Diabetes Dataset\\HUPA0001P.csv', 'C:\\Users\\Pravallika Dheshidi\\OneDrive\\Documents\\GitHub\\team9_PyCoders_PythonHackathon_MAY2026\\HUPA-UC Diabetes Dataset\\HUPA0002P.csv', 'C:\\Users\\Pravallika Dheshidi\\OneDrive\\Documents\\GitHub\\team9_PyCoders_PythonHackathon_MAY2026\\HUPA-UC Diabetes Dataset\\HUPA0003P.csv', 'C:\\Users\\Pravallika Dheshidi\\OneDrive\\Documents\\GitHub\\team9_PyCoders_PythonHackathon_MAY2026\\HUPA-UC Diabetes Dataset\\HUPA0004P.csv', 'C:\\Users\\Pravallika Dheshidi\\OneDrive\\Documents\\GitHub\\team9_PyCoders_PythonHackathon_MAY2026\\HUPA-UC Diabetes Dataset\\HUPA0005P.csv']

In [12]:
file_names = [os.path.basename(f) for f in files]
print(file_names[:5])

['HUPA0001P.csv', 'HUPA0002P.csv', 'HUPA0003P.csv', 'HUPA0004P.csv', 'HUPA0005P.csv']

In [15]:
patient_files = [f for f in files if os.path.basename(f).startswith("HUPA")] # just taking files starting with HUPA
print("Patient monitoring files:", len(patient_files))

Patient monitoring files: 25

In [16]:
all_data = []

for file in patient_files:
    df = pd.read_csv(file, sep=';')
    
    patient_id = os.path.basename(file).replace(".csv","")
    df["Patient_ID"] = patient_id
    
    all_data.append(df)

master_df = pd.concat(all_data, ignore_index=True)

In [17]:
master_df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID
0,2018-06-13T18:40:00,332.0,6.3595,82.322835,34.0,0.091667,0.0,0.0,HUPA0001P
1,2018-06-13T18:45:00,326.0,7.7280,83.740157,0.0,0.091667,0.0,0.0,HUPA0001P
2,2018-06-13T18:50:00,330.0,4.7495,80.525180,0.0,0.091667,0.0,0.0,HUPA0001P
3,2018-06-13T18:55:00,324.0,6.3595,89.129032,20.0,0.091667,0.0,0.0,HUPA0001P
4,2018-06-13T19:00:00,306.0,5.1520,92.495652,0.0,0.075000,0.0,0.0,HUPA0001P

In [18]:
print(master_df.columns)

Index(['time', 'glucose', 'calories', 'heart_rate', 'steps', 'basal_rate',
       'bolus_volume_delivered', 'carb_input', 'Patient_ID'],
      dtype='object')

In [22]:
meta_path = os.path.join(
    extract_folder,
    "HUPA-UC Diabetes Dataset",
    "T1DM_patient_sleep_demographics_with_race.csv"
)

meta = pd.read_csv(meta_path)

print(meta.head())
print(meta.columns)

  Patient_ID  Age  Gender             Race  Average Sleep Duration (hrs)  \
0  HUPA0001P   34    Male            Other                           6.3
1  HUPA0002P   49    Male         Hispanic                           6.6
2  HUPA0003P   64    Male            Black                           5.3
3  HUPA0004P   34  Female  Native American                           5.2
4  HUPA0005P   49    Male  Native American                           5.8

   Sleep Quality (1-10)  % with Sleep Disturbances
0                   4.5                         80
1                   4.4                         40
2                   5.2                         70
3                   6.9                         60
4                   7.9                         30
Index(['Patient_ID', 'Age', 'Gender', 'Race', 'Average Sleep Duration (hrs)',
       'Sleep Quality (1-10)', '% with Sleep Disturbances'],
      dtype='object')

In [23]:
master_df = master_df.merge(meta, on="Patient_ID", how="left") # merging sleep demographics with the mater data frame

In [24]:
master_df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,2018-06-13T18:40:00,332.0,6.3595,82.322835,34.0,0.091667,0.0,0.0,HUPA0001P,34,Male,Other,6.3,4.5,80
1,2018-06-13T18:45:00,326.0,7.7280,83.740157,0.0,0.091667,0.0,0.0,HUPA0001P,34,Male,Other,6.3,4.5,80
2,2018-06-13T18:50:00,330.0,4.7495,80.525180,0.0,0.091667,0.0,0.0,HUPA0001P,34,Male,Other,6.3,4.5,80
3,2018-06-13T18:55:00,324.0,6.3595,89.129032,20.0,0.091667,0.0,0.0,HUPA0001P,34,Male,Other,6.3,4.5,80
4,2018-06-13T19:00:00,306.0,5.1520,92.495652,0.0,0.075000,0.0,0.0,HUPA0001P,34,Male,Other,6.3,4.5,80